# Generated by Django 3.2.4 on 2021-06-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgoapp_ebikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminvisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('mobile_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('bikename', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=100)),
                ('dealer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgoapp_ebikes.dealer')),
            ],
        ),
    ]
